provide use_lxd parameter
samuelmeuli/action-snapcraft pull request #4
Opened 2020-02-16 18:26 UTC by casperdcl

Gives this action the ability to install and set up `lxd` (otherwise `snapcraft` doesn't seem to be able to build anything).

- [x] Document that `multipass` is not supported in GitHub's VMs
- [x] Get the action to install `lxd` (based on optional `with: use_lxd: true` since it may add ~10 in to build time)
- fixes #2

2020-02-16 18:27 UTC, casperdcl commented
cc @popey

2020-02-17 05:00 UTC, samuelmeuli commented on index.js
> +	const use_lxd = process.env.INPUT_USE_LXD;
Same as https://github.com/samuelmeuli/action-snapcraft/pull/5#discussion_r379985040

2020-02-17 05:13 UTC, samuelmeuli requested changes
LGTM. Could you please run the `yarn lint` and `yarn format` scripts, too?

I'll see how we can get the checks to pass for PRs. And if the new test you added works, we can merge this :)

2020-02-18 02:50 UTC, samuelmeuli approved these changes

2020-02-18 03:13 UTC, casperdcl commented
No need to force push, I already fixed all conflicts

2020-02-18 03:14 UTC, samuelmeuli commented
I only merged in the changes from `master`. I'd like to see whether all workflows now pass (except for the lint workflow)

2020-02-18 03:17 UTC, casperdcl commented
Right, rebased again

2020-02-18 03:35 UTC, merged

2020-02-18 03:36 UTC, samuelmeuli commented
Thanks a lot for your contributions, @casperdcl! 🙂 I'll tag a new release soon.